Admin/Admin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import home,error_404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^client/', include("clients.urls")),
    url(r'^project/', include("projects.urls")),
    url(r'^$',home,name='home'),


]
handler404 = error_404

Admin/clients/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import logout,LoginView,DashboardView,ShowView,Create,edit_password,edit,EditSocialClass

app_name = 'client'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
    url(r'^create/$', Create.as_view(), name='create'),
    url(r'^show/(?P<username_url>\w+)/$', ShowView.as_view(), name='show'),
    url(r'^edit/$', edit, name='edit'),
    url(r'^edit/password/$', edit_password, name='edit_password'),
    url(r'^edit/social/$', EditSocialClass.as_view(), name='edit_social'),

    ]

Admin/clients/models.py
from __future__ import unicode_literals
from django.db import models

from django.contrib.auth.models import User

class Client(models.Model):
	user1 = models.OneToOneField(User, on_delete = models.CASCADE)
	job = models.CharField(max_length=100,default="")
	bio = models.TextField(max_length=200,default="")

	def __str__(self):
		return self.user1.username

class SocialNetwork(models.Model):
	user = models.OneToOneField(User,on_delete = models.CASCADE)
	facebook = models.URLField(blank=True, null=True)
	twitter = models.URLField(blank=True, null=True)
	github = models.URLField(blank=True)
	linkedin = models.URLField(blank=True)

	def __str__(self):
		return self.user.username
    

Admin/clients/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Client,SocialNetwork

#Const
ERROR_MESSAGE_USER = {'required': 'El username es nesesario',
'unique':'El username ya se encuentra registrado','invalid':'Ingrese un username valido'}
ERROR_MESSAGE_PASSWORD = {'required':'El password es necesario'}
ERROR_MESSAGE_EMAIL = {'required': 'El username es nesesario',
'invalid':'Ingrese un correo valido'}

#Functions
def password_validation(value_password):
	if len(value_password) < 5:
		raise forms.ValidationError('The password requires minimun 5 characters')

#Class
class LoginUserForm(forms.Form):
	username = forms.CharField(max_length=30)
	password = forms.CharField(max_length=20, widget=forms.PasswordInput())

	def __init__(self, *args, **kwargs):
	    super(LoginUserForm, self).__init__(*args, **kwargs)
	    self.fields['username'].widget.attrs.update({'id':'username_login','class':'input_login'})
	    self.fields['password'].widget.attrs.update({'id':'username_login','class':'input_login'})
class CreateUserForm(forms.ModelForm):
	username = forms.CharField(max_length=30, error_messages=ERROR_MESSAGE_USER)
	password = forms.CharField(max_length=20, widget=forms.PasswordInput(),error_messages=ERROR_MESSAGE_PASSWORD)
	email = forms.CharField(error_messages=ERROR_MESSAGE_EMAIL)

	def __init__(self, *args, **kwargs):
	    super(CreateUserForm, self).__init__(*args, **kwargs)
	    self.fields['username'].widget.attrs.update({'id':'username_create'})
	    self.fields['password'].widget.attrs.update({'id':'password_login'})
	    self.fields['email'].widget.attrs.update({'id':'email_create'})

	def clean_email(self):
		email = self.cleaned_data.get('email')
		if User.objects.filter(email=email).count():
			raise forms.ValidationError('El email debe de ser unico.')
		return email


	class Meta:
		model= User
		fields =('username','password','email')
class EditUserForm(forms.ModelForm):
	username = forms.CharField(max_length=30, error_messages=ERROR_MESSAGE_USER)
	email = forms.CharField(error_messages=ERROR_MESSAGE_EMAIL)
	first_name = forms.CharField(label='Nombre')
	last_name = forms.CharField(label='Apellido')
	class Meta:
		model = User
		fields =('username','email','first_name','last_name')

	def clean_email(self):
		email = self.cleaned_data.get('email')
		if User.objects.filter(email=email).exclude(pk=self.instance.id).count():
			raise forms.ValidationError('El email debe de ser unico.')
		return email
class EditPasswordForm(forms.Form):
	password = forms.CharField(label='Contraseña actual', max_length=20, widget=forms.PasswordInput())
	new_password = forms.CharField(label='Nueva contraseña', max_length=20, widget=forms.PasswordInput(),validators=[password_validation])
	repeat_password = forms.CharField(label='Repetir nueva contraseña',max_length=20, widget=forms.PasswordInput(),validators=[password_validation])

	def clean(self):
		clean_data = super(EditPasswordForm,self).clean()
		password1 = clean_data['new_password']
		password2 = clean_data['repeat_password']
		if password1 != password2:
			raise forms.ValidationError('los passwords no coinciden')
class EditClientForm(forms.ModelForm):
	job = forms.CharField(label='Trabajo actual',required=False)
	bio = forms.CharField(label='Biografía', widget=forms.Textarea,required=False)

	class Meta:
		model = Client
		exclude = ['user1']

		def __init__(self, *args, **kwargs):
			super(EditClientForm, self).__init__(*args, **kwargs)
			self.fields['job'].widget.attrs.update({'id':'job_edit_client','class':'validate'})
			self.fields['bio'].widget.attrs.update({'id':'bio_edit_client','class':'validate'})

class EditSocialForm(forms.ModelForm):
    class Meta:
        model = SocialNetwork
        exclude = ['user']


    
			

Admin/clients/views.py
from django.contrib.auth import authenticate,update_session_auth_hash,login as login_django,logout as logout_django
from .forms import LoginUserForm,CreateUserForm,EditUserForm,EditPasswordForm,EditClientForm,EditSocialForm
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.generic import View,DetailView,CreateView
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from .models import Client,SocialNetwork


class ShowView(DetailView):
	model = User
	template_name = 'clients/show.html'
	slug_field ='username'
	slug_url_kwarg = 'username_url'

class LoginView(View):
	form = LoginUserForm()
	message = None
	template = 'clients/login.html'

	def get(self,request,*args,**kwargs):
		if request.user.is_authenticated():
			return redirect('client:dashboard')
		return render(request,self.template, self.get_context())

	def post(self,request,*args,**kwargs):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username,password=password)	
		if user is not None:
			login_django(request,user)
			return redirect('client:dashboard')
		else:
			self.message = "User or password incorrect"
		return render(request,'clients/login.html', self.get_context())

	def get_context(self):
		return {'form':self.form,'message':self.message}

class DashboardView(LoginRequiredMixin,View):
	login_url = 'client:login'
	def get(self,request,*args,**kwargs):
		return render(request,'clients/dashboard.html', {})
		
class Create(CreateView):
	success_url = reverse_lazy('client:login')
	template_name = 'clients/create.html'
	model = User
	form_class = CreateUserForm

	def form_valid(self,form):
		self.object = form.save(commit=False)
		self.object.set_password(self.object.password)
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

class EditSocialClass(LoginRequiredMixin,UpdateView,SuccessMessageMixin):
	login_url ='client:login'
	model = SocialNetwork
	template_name = 'clients/edit_social.html'
	form_class = EditSocialForm
	success_url = reverse_lazy('client:edit_social')
	success_message = "Datos actualizados exitosamente"

	def get_object(self, queryset = None):
		return self.get_social_instance()

	def get_social_instance(self):
		try:
			return self.request.user.socialnetwork
		except:
			return SocialNetwork(user = self.request.user)


def edit_password(request):
	message = None
	form = EditPasswordForm(request.POST or None)
	if request.method =='POST':
		if form.is_valid():
			current_password = form.cleaned_data['password']
			new_password = form.cleaned_data['new_password']
			if authenticate(username=request.user.username, password=current_password):
				request.user.set_password( new_password )
				request.user.save()
				update_session_auth_hash(request,request.user)
				messages.success(request,'password actualizado !')
			else:
				messages.error(request,'No se puede actualizar el password')
	context = {'form':form}
	return render(request,'clients/edit_password.html',context)

@login_required(login_url = 'client:login')	
def logout(request):
	logout_django(request)
	return redirect('client:login')

@login_required(login_url = 'client:login')
def edit(request):
	form_client = EditClientForm(request.POST or None, instance = client_instance(request.user))	#esto es en shell
	form_user = EditUserForm(request.POST or None, instance = request.user)
	if request.method =='POST':
		if form_client.is_valid() and form_user.is_valid():
			form_client.save()
			form_user.save()
			messages.success(request,'Se actualizarón los datos !')

	context = {
		'form_client':form_client,
		'form_user':form_user
	}
	return render(request,'clients/edit.html',context)


def client_instance(user):
	try:
		return user.client
	except:
		return Client(user1 = user)
	

Admin/templates/clients/bases/base_client.html
{% load staticfiles %}
<!DOCTYPE htlm>
<html>
<head>
	<meta charset="UTF-8">
	
	<title> {% block title %} {% endblock %} </title>

	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
     
   {% block scripts %} {% endblock %} 

</head>
<body>
	<header>
	  <div class="navbar-fixed">
	    <nav>
	      <div class="nav-wrapper blue ">
	      	<a href="{% url 'client:dashboard' %}" class="brand-logo">Administrador</a>
	        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>       
	        <ul class="right hide-on-med-and-down lighten-2">
	          <li><a href="{% url 'client:edit' %}">Editar</a></li>
	          <li><a href="{% url 'client:logout' %}">Salir</a></li>          
	        </ul>
	      </div>
	    </nav>
	   </div>
	</header>

	{% if messages %}
		<div class="center-align">
			<ul class="messages">
	    	{% for message in messages %}
	    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    	{% endfor %}
			</ul>
		</div>
	{% endif %}

	{% block content %} {% endblock %} 
	
	{% block footer %} {% endblock %} 


</body>
</html>

Admin/templates/clients/bases/edit2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} {% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "client_style.css" %}">
</head>
<body>
<h3>{% block subtitle %}
	
{% endblock subtitle %}</h3>
<a href="{% url 'client:login' %}">login</a>
<a href="{% url 'client:edit_password' %}">actualizar password</a>
<a href="{% url 'client:edit' %}">editar usuario</a>
<a href="{% url 'client:create' %}">crear cliente</a>
<a href="{% url 'client:logout' %}">salir</a>
{% if messages %}
	<ul>
	{% for message in messages %}
	<li {% if message.tags %} class="{{message.tags}}_message" {% endif %} >
	{{ message }}</li>	
	{% endfor %}
	</ul>
{% endif %}

<a href="{% url 'client:dashboard'%}">dashboard</a> 
{% block content %}
	
{% endblock content %}
</body>
</html>

Admin/templates/clients/bases/edit_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} {% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "client_style.css" %}">
</head>
<body>
<h3>{% block subtitle %}
	
{% endblock subtitle %}</h3>
<a href="{% url 'client:login' %}">login</a>
<a href="{% url 'client:edit_password' %}">actualizar password</a>
<a href="{% url 'client:edit' %}">editar usuario</a>
<a href="{% url 'client:create' %}">crear cliente</a>
<a href="{% url 'client:logout' %}">salir</a>
{% if messages %}
	<ul>
	{% for message in messages %}
	<li {% if message.tags %} class="{{message.tags}}_message" {% endif %} >
	{{ message }}</li>	
	{% endfor %}
	</ul>
{% endif %}

<a href="{% url 'client:dashboard'%}">dashboard</a> 
{% block content %}
	
{% endblock content %}
</body>
</html>