Admin/Admin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import home,error_404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^client/', include("clients.urls")),
    url(r'^project/', include("projects.urls")),
    url(r'^$',home,name='home'),


]
handler404 = error_404

Admin/clients/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import logout,LoginView,DashboardView,ShowView,Create,edit_password,edit,EditSocialClass

app_name = 'client'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
    url(r'^create/$', Create.as_view(), name='create'),
    url(r'^show/(?P<username_url>\w+)/$', ShowView.as_view(), name='show'),
    url(r'^edit/$', edit, name='edit'),
    url(r'^edit/password/$', edit_password, name='edit_password'),
    url(r'^edit/social/$', EditSocialClass.as_view(), name='edit_social'),

    ]

Admin/templates/bases/base_admin.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} {% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
	{% block scripts %}	
	{% endblock  %}

</head>
<body>
	<header>
	<nav>
    <div class="nav-wrapper blue">
      <a href="#" class="brand-logo">Administrador</a>
      	<ul id="nav-mobile" class="right hide-on-med-and-down">
        	<li><a href="{% url 'client:login' %}">Iniciar sesión</a></li>
       		<li><a href="{% url 'client:create' %}">Regístrate</a></li>
      	</ul>
    </div>
  	</nav>
  	</header>


{% if messages %}
	<ul>
	{% for message in messages %}
	<li {% if message.tags %} class="{{message.tags}}_message" {% endif %} >
	{{ message }}</li>	
	{% endfor %}
	</ul>
{% endif %}
{% block content %}
	
{% endblock content %}

{% block footer %}
	
{% endblock footer %}
</body>
</html>