Admin/Admin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import home,error_404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^client/', include("clients.urls")),
    url(r'^project/', include("projects.urls")),
    url(r'^$',home,name='home'),


]
handler404 = error_404

Admin/projects/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import CreateProjectClass,ListClass, ShowClass,edit

app_name = 'project'

urlpatterns = [
    url(r'^create/$', CreateProjectClass.as_view(), name='create'),
    url(r'^my/projects/$', ListClass.as_view(), name='my_projects'),
    url(r'^show/(?P<slug>[\w-]+)/$', ShowClass.as_view(), name='show'),
    url(r'^edit/(?P<slug>[\w-]+)/$', edit, name='edit'),


]

Admin/projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from status.models import Status
from django.utils import timezone

import datetime

class Project(models.Model):

	#user = models.ForeignKey(User, on_delete = models.CASCADE)
	title = models.CharField(max_length=60)
	description = models.TextField()
	dead_line = models.DateField()
	create_date = models.DateField(default = datetime.date.today)
	slug = models.CharField(max_length=50,default='')

	def __str__(self):
		return self.title

	def validate_unique(self, exclude=None):
		self.slug = self.create_slug_field(self.title)
		if Project.objects.filter(slug = self.slug).exclude(pk = self.id).exists():
			raise ValidationError('Un proyecto con el mismo titulo ya se encuentra registrado.')

	def create_slug_field(self, value):
		return value.lower().replace(" ", "-")

	def get_id_status(self):
		return self.projectstatus_set.last().status_id

	def get_status(self):
		return self.projectstatus_set.last().status


class ProjectStatus(models.Model):
	project = models.ForeignKey(Project)
	status = models.ForeignKey(Status)
	create_date = models.DateTimeField(default = timezone.now)

	class Meta:
		verbose_name_plural='ProjectStatus'

class ProjectPermission(models.Model):
	title = models.CharField(max_length=50)
	description = models.TextField()
	level = models.IntegerField()
	create_deate = models.DateField(default= timezone.now)

	def __str__(self):
		return self.title

class ProjectUser(models.Model):
	project = models.ForeignKey(Project, on_delete = models.CASCADE)
	user = models.ForeignKey(User)
	permission = models.ForeignKey(ProjectPermission)
	create_date = models.DateField(default= timezone.now)

	def getProject(self):
		return self.project


    


		
        
    

Admin/projects/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Project
import datetime
class CreateProjectForm(forms.ModelForm):

	title = forms.CharField(label='Título', max_length=60,required=True)
	description = forms.CharField(label='Descripción',required=False, widget=forms.Textarea )
	dead_line = forms.DateField(initial=datetime.date.today)

	class Meta:
		model = Project
		fields = ('title','description','dead_line')

Admin/projects/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView,ListView,DetailView
from .forms import CreateProjectForm
from .models import Project, ProjectUser
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from status.models import Status
from status.forms import StatusChoiceForm
from django.contrib import messages
from django.db import transaction
from .permission_user import EPermission

class CreateProjectClass(CreateView, LoginRequiredMixin):
	login_url = 'client:login'
	model = Project
	template_name = 'project/create.html'
	form_class = CreateProjectForm
	
	@transaction.atomic		#succes si todo se cumple y si no hace un rolback es decir al estado anterior
	def create_objects(self):
		self.object.save()
		self.object.projectstatus_set.create(status = Status.getDefaultStatus())	#crea un status por defaul despues de guardar
		self.object.projectuser_set.create(user= self.request.user, permission_id = EPermission.maker )	

	def form_valid(self, form):
		self.object = form.save(commit = False)
		self.create_objects()
		return HttpResponseRedirect(self.getUrlProject())

	def getUrlProject(self):
		return reverse_lazy('project:show', kwargs = {'slug': self.object.slug})

class ListClass(ListView, LoginRequiredMixin):
	login_url = 'client:login'
	template_name = 'project/own.html'
	paginate_by = 5

	def get_queryset(self):
		return ProjectUser.objects.filter(user = self.request.user)

class ShowClass(DetailView):
	model = Project
	template_name = 'project/show.html'

@login_required(login_url = 'client:login')
def edit(request, slug=''):
	project = get_object_or_404(Project, slug=slug)
	form_project = CreateProjectForm(request.POST or None, instance = project)
	forms_status = StatusChoiceForm(request.POST or None, initial={'status': project.get_id_status()})	#Ultimo status de proyecto

	if request.method == 'POST':
		if form_project.is_valid() and forms_status.is_valid():
			selection_id = forms_status.cleaned_data['status'].id	
			form_project.save()

			if selection_id != project.get_id_status():
				project.projectstatus_set.create(status_id = selection_id)
			messages.success(request, 'Datos actualizados')

	context = {
	'form_project': form_project,
	'forms_status': forms_status
	}
	return render(request, 'project/edit.html', context)

		

Admin/templates/project/create.html
{% extends "clients/bases/base_client.html" %}

{% block title %}
	Crear Proyecto
{% endblock title %}

{% block scripts %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static "css/forms.css" %}">
{% endblock  %}

{% block content %}

<div class="class_container_form">
  <form method="post" action="">
	{% csrf_token %}
	{% include "includes/_forms.html" with form=form only %}

	<input class="btn #9e9e9e blue" type="submit" value="Crear">
</form>
</div>
{% endblock  %}

Admin/templates/project/edit.html
{% extends "clients/bases/base_client.html" %}

{% block title %}
	Editar Proyecto
{% endblock title %}

{% block scripts %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static "css/forms.css" %}">
{% endblock  %}

{% block content %}

<div class="class_container_form">
  <form method="post" action="">
	{% csrf_token %}
	{% include "includes/_forms.html" with form=form_project only %}

	{% include "includes/_forms.html" with form=forms_status only %}

	<input class="btn #9e9e9e blue" type="submit" value="Actualizar">
</form>
</div>
{% endblock  %}
{% block footer %}
	
{% endblock footer %}

Admin/templates/project/own.html
{% extends "clients/bases/base_client.html" %}

{% block title %}
	Mis Proyectos
{% endblock title %}

{% block scripts %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static "css/forms.css" %}">
{% endblock  %}

{% block content %}
	<a href="{% url 'project:create' %}">Crear Proyecto</a>

{% for project_user in object_list %}

{% with project_user.getProject as project  %}
	<h4>
		<li>
		<a href="{% url 'project:show' project.slug %}"> {{project.title}}</a>
		</li>
	</h4> 
{% endwith %}

{% endfor %}

{% endblock  %}

Admin/templates/project/show.html
{% extends "clients/bases/base_client.html" %}

{% block title %}
	Mis Proyectos
{% endblock title %}

{% block scripts %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static "css/forms.css" %}">
{% endblock  %}

{% block content %}

<h2>{{project.title}}</h2>
<a href="{% url 'project:edit' project.slug %}">Editar</a>


{% endblock  %}